# Generated by Django 4.0.2 on 2022-03-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('image', models.URLField(default='https://image.zmenu.com/menupic/4612715/072d7a11-2c4d-4d2d-bd6b-7b32b10d9721.jpg')),
            ],
        ),
    ]
